version: '3.1'

services:

  ghost:
    image: ghost:4-alpine
    restart: always
    expose:
      - 2368
    environment:
      VIRTUAL_HOST: api.ethancorcoran.com
      VIRTUAL_PORT: 2368
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      url: https://api.ethancorcoran.com

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ghostdb:/var/lib/mysql

volumes:
  ghostdb:

networks:
  default:
    external:
      name: nginx-proxy